# Generated by Django 5.1.6 on 2025-02-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_otprequest_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otprequest',
            old_name='created_at',
            new_name='created',
        ),
    ]
